services:
  s3n-browser:
    image: s3n-browser:latest
    ports:
    - "80:3000"
    environment:
      - NODE_ENV=production
      - S3_ENDPOINT_URL={ENDPOINT_URL}
      - S3_ACCESS_KEY_ID={YOUR_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY={YOUR_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME={BUKET_NAME}
      - S3_REGION={REGION}
      - SIGNING_SERVICE_URL={SIGNING_SERVICE_URL}

