import { AppStoreProvider } from '@/context/app-store-provider';
import { PersistedAppStoreProvider } from '@/context/persisted-app-store-provider';
import { ThemeProvider } from '@/context/theme-provider';
import { validateEnvironmentVariables } from '@/lib/configuration/environment-variables';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import { Toaster } from 'sonner';

(function OnAppInitialize() {
  validateEnvironmentVariables();
})();

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <PersistedAppStoreProvider>
            <AppStoreProvider>
              {children}
              <Toaster richColors={true} />
            </AppStoreProvider>
          </PersistedAppStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
